### ISSUE TITLE
stack issue

### ISSUE THREAD

**Issue by kwannoel** [kwannoel/thoughts#1]
Running deploy shell script via hakyll deploy command fails with this bug: https://github.com/commercialhaskell/stack/issues/5000.

To reproduce, run in nixos19.09, 
> stack exec thoughts deploy

A possible solution is here
https://github.com/cdepillabout/termonad/pull/131/files

**Comment by domenkozar** [comment]
Note that https://github.com/commercialhaskell/stack/issues/5000 was fixed in stack master.
